apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccount:
    name: collector
  outputs:
    - name: cloudwatch-audit
      type: cloudwatch
      cloudwatch:
        region: {{ .Values.awsRegion }}
        groupName: '{{ .Values.clusterName }}/{.log_type||"unlabeled"}'
        authentication:
          type: iamRole
          iamRole:
            roleARN:
              key: role_arn
              secretName: cloudwatch-credentials
            token:
              from: serviceAccount
  pipelines:
    - name: audit-to-cloudwatch
      inputRefs:
        - audit
      outputRefs:
        - cloudwatch-audit
