apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-log-forwarding
  namespace: argocd
spec:
  project: default
  source:
    # Update repoURL to match your Git remote.
    repoURL: ""
    targetRevision: HEAD
    path: chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
